### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by FionaMoon** [Changlu-Xu/singlecell_erythroid#1]
Hi ,
Thank you for sharing code of your article! It's really interesting to know erythroblast can have immune function.
I try to download the corresponding data of your article from `https://doi.org/10.6084/m9.figshare.19747204.v1` but failed.
```
> Ery_integrated <- load("processed_data/Ery.integrated.RData")
> Ery_integrated
[1] "Ery.integrated_counts_matrix"   "Ery.integrated.cell.embeddings"
[3] "Ery.integrated_meta_info"      
> class(Ery_integrated)
[1] "character"
```
It seems that these files are empty. Can you re-upload the data?

Thank you inadvance!

Fiona

**Comment by Changlu-Xu** [comment]
> 
Rdata files are available at https://doi.org/10.6084/m9.figshare.19747204.v1
please download firstly and then load in R.

**Comment by FionaMoon** [comment]
Thank you for your reply!
I've already download files.
