### ISSUE TITLE
How to define immune-Ery in bown marrow?

### ISSUE THREAD

**Issue by FionaMoon** [Changlu-Xu/singlecell_erythroid#2]
Dear author,
 I try to learn how to find immune-Ery in bone marrow sample from your code. I’ve download your BM data and integrate sample by `Sample_ID` which provided by your metadata.
I find that it's difficult to find 4 clusters of BM data , because your article just provide details (such PC and resoultion) about  YS, FL PT-UCB samples. 

I really want to make sure whether immune-Ery exists in healthy people. My research is about multiple myeloma and I want to see if immune-Ery group expand when people get multiple myeloma.

So can your provide me more details about how to define immune-Ery in BM sample?

Thank you so much!

**Comment by Changlu-Xu** [comment]
The Rdata in https://doi.org/10.6084/m9.figshare.19747204.v1 include the cluster information, and we first integrated the dataset based on "Sample_ID", then top 10 PCs and the resolution = 0.2. The immune-Ery was defined based on the high expression of immune-related genes.

**Comment by FionaMoon** [comment]
Thank you!
